version: '3'
services:
  wiremock:
    image: 'wiremock/wiremock:latest'
    container_name: my_wiremock
    ports:
      - 8080:8080
    entrypoint:
      [
        '/docker-entrypoint.sh',
        '--global-response-templating',
        '--disable-gzip',
        '--verbose',
      ]
