name: E2E Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - run: npm ci
      - run: docker compose up -d
      - run: npx playwright install
      - run: npx playwright install --with-deps
      - run: npx playwright test
